using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RandomNPCDialogue : MonoBehaviour
{
    public string[] npcDialog = new string[] { 
        "where can i get a drink around here?",
        "I rolled 28 for initiative",
        "pew pew",
        "I was an adventurer like you 'till I took a pin to the knee",
        "Do you get to the floor district often? Oh, what am I saying - Of course you don't.",
        "Did you ever hear the story of Rat Plagueis the wise?",
        "This material is protected by copyright and has been copied by and solely for the educational purposes of the University under license.",
        "Have you submitted your status report to the administrator today?",
        "Do you know who ate all the donuts?",
        "Join my clan",
        "Can we get much higher?",
        "Fishing level?",
        "rawr xD uwu",
        "I'm a veteran of the great cat war of 03' you know?",
        "I'm the giant rat that makes all of the rules.",
        "Lets see what kind of trouble we can get ourselves into.",
        "I know ka-rat-e",
        "piiiikaaaaachUuuuuUuUuuuu!!!!! (no reference to Pokemon Inc. for legal reasons)",
        "You wanna know how I got these scars?",
        "Rats are various medium-sized, long-tailed rodents. Species of rats are found throughout the order Rodentia, but stereotypical rats are found in the genus Rattus.",
        "The normal rat is like this-",
        "You ain't nothing but a houndrat, sniffling all the time",
        "I have the bubonic plague",
        "I used to work at Chuck E Cheese, then I got fired in 1997 and a stupid mouse took my place",
        "2020 was my year",
        "Bread, milk, eggs...",
        "I'm not really a cheese rat, i prefer crackers",
        "I have 30ft of darkvision",
        "Am i a rat or a mouse?",
        "I tested positive on my RAT test",
        "My pronouns are rat/rat",
        "We're holding Big E Cheese hostage",
        "Hello World",
        "I'm an NPC",
        "Local gym rats in the area, click here to talk to them",
        "Pay $14.99 a month for ultimate unlimited ad-free rattic",
        "I heard the artist rat does good drawing of fruit and vegetables.",
        "Rattic would like to take a moment to thank today's sponsor Rat Shadow Legends",
        "The lab rat is always breaking things.",
        "The gym rat is so buff, i wonder what he eats.",
        "Did you see that human? Was he looking for something up here in the attic?",
        "The Emo Rat is secretly a capitalist",
        "That dog is quite friendly",
        "The mystic rat can tell see your future",
        "I was the last customer at the fashionista before she ran out of supplies. Dont i look great?",
        "Yass queen that outfit slays",
        "i have a confession.... i'm in love with a mouse",
        "That chef does good dinners, but also snacks too.",
        "Fake Rat has some... issues",
        "Hey... pst.. there is a hidden item behind me NOT!",
        "HELP! THEY GLUED ME HERE",
        "HELP! My step bro is stuck in glue",
        "I won’t be playable but everyone will remember me as a very important character",
        "The brotherhood knows what you've done",
        "Rat Jesus is that you?",
        "go touch grass guys",
        "Lok'tar Ogar",
        "Hello, would you like to know about eternal life? I am totally not suspicious",
        "MMmmmm yummmy sewer food",
        "I just signed out",
        "Did you hear? Even RaThanos is afraid of the gym rat",
        "Want to buy some crypto rattacy?",
        "And they wont stop coming and they wont stop coming ......",
        "meta dev discussion being held right now",
        "Most of this game is filler"
    };
}
